### ISSUE TITLE
Corruptive behavior on failed pack attempts on BSPs

### ISSUE THREAD

**Issue by thacaretaker** [drinklc/AutoBSPpackingTool#3]
[INFO] Packing assets...
[ERROR] Packing was forced to stop due to bspzip.exe error (reason: unknown; exit code: 1); bspzip.exe log saved at: G:/exgengmod/bsppacker/cache/bspzip_log.txt

The log itself gives very little information.
Dump file:
![image](https://github.com/user-attachments/assets/979668fc-1271-45c9-ab43-e73c1efbf6c0)

What results in the BSP you've attempted to pack/load, is that it cannot be loaded by any program of similar utility and returns empty lumps (BSPSrc, any decompiler, VIDE, etc, while keeping file size. As far as why it's failing to pack for me, not a clue, but I thought it was interesting enough behavior to report.

**Comment by drinklc** [comment]
From the description, it seems like the problem you're encountering is related to bspzip.exe rather than something directly tied to the program itself. If you'd like, you can try using the **--use-native-tools** option, which will make the program use built-in tools instead of external ones, such as bspzip.exe in your case.

Also, the program automatically creates a backup file (\<mapname\>.bsp.backup) unless the **--no-backup** option is specified.

Let me know if that helps.

**Comment by thacaretaker** [comment]
Interesting, I had success with using VIDE/Pakrat together later down the line. I didn't use the program via the command line however, so I suppose I'll give it a go next time I run a full compile and try out --use-native-tools.
